app = 'solome-bot'
primary_region = 'ams'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4

[checks]
  [checks.alive]
    grace_period = '30s'
    interval = '15s'
    method = 'get'
    path = '/health'
    port = 8080
    timeout = '10s'
    type = 'http'
